version: '3'
services:
  #db:
    #image: mysql:5.7
    #environment:
      #MYSQL_ROOT_PASSWORD: password
      #MYSQL_DATABASE: root
    #ports:
      #- "3306:3306"
  app:
    build: .
    command: bundle exec puma -C config/puma.rb -e production
    volumes:
      - .:/myapp
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
      - log-data:/myapp/log

  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
    ports:
      - 80:80

volumes:
  # mysql-data:
  public-data:
  tmp-data:
  log-data:
